### ISSUE TITLE
KeyError for 2nd document to be filled

### ISSUE THREAD

**Issue by Knowaaaa** [altaurog/pdfforms#10]
Currently when I try running `pdfforms fill pdfFill.csv` the first document that I have created in the pdfFill.csv gets filled out and created, but it gives a KeyError for the second document.  
  
```
C:\Python37>pdfforms fill pdfFill.csv
approval.pdf
LeadPamphletReceipt.pdf
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pdfforms.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\pdfforms\pdfforms.py", line 167, in main
    args.func(args)
  File "c:\python37\lib\site-packages\pdfforms\pdfforms.py", line 33, in fill_pdfs
    for filepath in fg:
  File "c:\python37\lib\site-packages\pdfforms\pdfforms.py", line 77, in fill_forms
    fdf_str = generate_fdf(field_defs[filepath], formdata)
KeyError: 'LeadPamphletReceipt.pdf'
```
Is it possible I am just formatting the document wrong or is the process for doing multiple documents different? If it helps, I am using Pandas to generate these CSV's before filling. 
  
Here is what the data looks like in pdfFill.csv where it transitions from approval.pdf to LeadPamphletReceipt.pdf:  
  

```
approval.pdf
...
...
28 | DATE
-- | --
29 | CUSTOMER NAME
13 | Cell Number
LeadPamphletReceipt.pdf
0 | Last Name
1 | Firstname
2 | Store
```

**Comment by altaurog** [comment]
It looks like the name `'LeadPamphletReceipt.pdf'` does not exactly match the pdf name that was generated in `fields.json` when you ran `pdfforms inspect`.  Please check `fields.json`.  Note the lookup is case sensitive.
