### ISSUE TITLE
Expecting password for a non-password pdf file

### ISSUE THREAD

**Issue by Pechimuthu77** [altaurog/pdfforms#11]
Hi, I am trying to inspect a PDF form downloaded file.

when I do that, it says incorrect owner password, but the file does not need any password to open, I can open it without any password on adobe.

Error Traceback.

`D:\Projects\Scraping\Fill pdf form>pdfforms inspect imm5669e.pdf
Error: Failed to open PDF file:
   imm5669e.pdf
   OWNER PASSWORD REQUIRED, but not given (or incorrect)
Errors encountered.  No output created.
Done.  Input errors, so no output created.
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\Scripts\pdfforms.exe\__main__.py", line 9, in <module>
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pdfforms\pdfforms.py", line 169, in main
    args.func(args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pdfforms\pdfforms.py", line 19, in inspect_pdfs
    field_defs[filename] = inspect_pdf_fields(filename)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pdfforms\pdfforms.py", line 54, in inspect_pdf_fields
    p = run(cmd, stdout=PIPE, universal_newlines=True, check=True)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pdftk', 'imm5669e.pdf', 'dump_data_fields', 'output', '-']' returned non-zero exit status 1.`

Please help

**Comment by Pechimuthu77** [comment]
solved by installing [qpdf](https://codeyarns.github.io/tech/2012-11-25-decrypt-an-encrypted-pdf-file-using-qpdf.html)
