### ISSUE TITLE
Getting a KeyError

### ISSUE THREAD

**Issue by developfast** [altaurog/pdfforms#16]
Just received this error: 

```bash
$ pdfforms fill test1.csv
f1040nr.pdf
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/bin/pdfforms", line 8, in <module>
    sys.exit(main())
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pdfforms/pdfforms.py", line 169, in main
    args.func(args)
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pdfforms/pdfforms.py", line 33, in fill_pdfs
    for filepath in fg:
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pdfforms/pdfforms.py", line 77, in fill_forms
    fdf_str = generate_fdf(field_defs[filepath], formdata)
KeyError: '\ufefff1040nr.pdf'
```

Have checked that the csv contains: 

```bash
f1040nr.pdf | Form 1040-NR
4 | First Name and Initial
5 | Last Name
6 | SSN
7 | Home address
...
```

The ```fields.json``` contains 
```bash 
{
    "f1040nr.pdf": {
        "0": {
            "type": "Button",
            "name": "topmostSubform[0].Page1[0].c1_01[0]",
            "flags": "0",
            "value": "Off",
...
```

Can't seem to debug this problem, is there a padding issue somewhere I am not aware of? Any help would be greatly appreciated.

**Comment by altaurog** [comment]
your csv file has a unicode byte order mark at the beginning (FEFF)
that should be removed

**Comment by developfast** [comment]
thanks a lot!
