### ISSUE TITLE
Add documentation about supported formats and pyexcel dependencies

### ISSUE THREAD

**Issue by dickermoshe** [altaurog/pdfforms#20]
I had to install `pyexcel-pdfr` manually from pip on first run. Is something missing from requirements ?
> Traceback (most recent call last):
  File "c:/Users/user/gha/gethomeasap/fill.py", line 3, in <module>
    for filepath in pdfforms.fill_pdfs(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfforms\pdfforms.py", line 63, in fill_pdfs
    sheet = spreadsheet.load_sheet(data_file, sheet_name, pyexcel_library)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfforms\spreadsheet.py", line 17, in load_sheet
    return pyexcel.get_sheet(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel\core.py", line 37, in get_sheet
    named_content = sources.get_sheet_stream(**keywords)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel\internal\core.py", line 22, in get_sheet_stream
    sheets = a_source.get_data()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel\plugins\sources\file_input.py", line 38, in get_data
    sheets = self.__parser.parse_file(self.__file_name, **self._keywords)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel\plugins\parsers\excel.py", line 19, in parse_file
    return self._parse_any(file_name, **keywords)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel\plugins\parsers\excel.py", line 40, in _parse_any
    sheets = get_data(anything, file_type=file_type, **keywords)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel_io\io.py", line 86, in get_data
    data, _ = _get_data(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel_io\io.py", line 105, in _get_data
    return load_data(**keywords)
    reader.open(file_name, **keywords)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel_io\reader.py", line 43, in open
    self.reader_class = NEW_READERS.get_a_plugin(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel_io\plugins.py", line 185, in get_a_plugin
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\lml\plugin.py", line 292, in load_me_now
    self.raise_exception(key)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyexcel_io\plugins.py", line 201, in raise_exception
    raise exceptions.SupportingPluginAvailableButNotInstalled(message)
pyexcel_io.exceptions.SupportingPluginAvailableButNotInstalled: Please install pyexcel-pdfr

**Comment by dickermoshe** [comment]
Add to readme that you must install `Ghostscript`. I got this message 

> OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html

**Comment by altaurog** [comment]
@dickermoshe first of all, thanks for your interest in pdfforms!  This was an oversight in the documentation, which I thought I’d included, but I see now there is no mention of it.  Please refer to the documentation on the [pyexcel plugin architecture](http://docs.pyexcel.org/en/latest/architecture.html).  Pyexcel’s support for multiple data formats is implemented in plugins which are distributed independently of the core library.  pdfforms depends only on pyexcel.  If you want support for csv, xlsx, or ods you can specify it as an extra like so: `pdfforms[xlsx]`.  But if you want to use any other pyexcel formats, then you will indeed need to install the desired pyexcel plugin and its dependencies on your own.
I will add all this to the documentation.

**Comment by altaurog** [comment]
@dickermoshe camelot and ghostscript are pyexcel-pdfr dependencies.  I don’t believe that ghostscript is a dependency of pdfforms or any of the officially supported pyexcel plugins (pyexcel-io, pyexcel-xlsx, pyexcel-ods).
