### ISSUE TITLE
Full path in 1st line of csv causes KeyError

### ISSUE THREAD

**Issue by andersonwinkler** [altaurog/pdfforms#21]
I receive a KeyError if the 1st line of the .csv contains the full path to the .pdf:

```
pdfforms fill --prefix /home/[REDACTED]/fill/ /home/[REDACTED]/values.csv
/home/[REDACTED]/form.pdf
Traceback (most recent call last):
  File "/home/[REDACTED]/.local/bin/pdfforms", line 10, in <module>
    sys.exit(main())
  File "/home/[REDACTED]/.local/lib/python3.7/site-packages/pdfforms/cli.py", line 127, in main
    args.func(args)
  File "/home/[REDACTED]/.local/lib/python3.7/site-packages/pdfforms/cli.py", line 33, in fill_pdfs
    value_transforms=value_transforms,
  File "/home/[REDACTED]/.local/lib/python3.7/site-packages/pdfforms/pdfforms.py", line 67, in fill_pdfs
    yield from fill.fill_forms(prefix, field_defs, form_data, flatten)
  File "/home/[REDACTED]/.local/lib/python3.7/site-packages/pdfforms/fill.py", line 36, in fill_forms
    fdf_str = fdf.generate_fdf(field_defs[filepath], formdata)
KeyError: '/home/[REDACTED]/form.pdf'
```

As soon as I replace the full path for just the filename, and run from the same directory that contains the form, the error disappears.

**Comment by andersonwinkler** [comment]
Actually, no. I did something wrong. There is no problem. My mistake.
