### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by andrewtmendoza** [altaurog/pdfforms#3]
Does pdfforms work on Windows? I'm getting the following error:

> (base) C:\Users\atm\Downloads\pdf test>pdfforms inspect "C:\Users\atm\Downloads\pdf test\OoPdfFormExample.pdf"
Traceback (most recent call last):
  File "c:\users\atm\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\atm\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\atm\Anaconda3\Scripts\pdfforms.exe\__main__.py", line 9, in <module>
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 160, in main
    args.func(args)
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 19, in inspect_pdfs
    field_defs[filename] = inspect_pdf_fields(filename)
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 53, in inspect_pdf_fields
    p = run(cmd, stdout=PIPE, universal_newlines=True, check=True)
  File "c:\users\atm\anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\atm\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\atm\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by altaurog** [comment]
Is pdftk on your `%PATH%`?

**Comment by andrewtmendoza** [comment]
Ah I didn't realize that PDFtk Server needed to be installed beforehand. Thanks!

I've encountered a new error when I try to fill a PDF using the CSV file:

> (base) C:\Users\atm\test>pdfforms fill "C:\Users\atm\Downloads\pdf test\test.csv"
Traceback (most recent call last):
  File "c:\users\atm\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\atm\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\atm\Anaconda3\Scripts\pdfforms.exe\__main__.py", line 9, in <module>
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 160, in main
    args.func(args)
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 30, in fill_pdfs
    field_defs = load_field_defs(args.field_defs)
  File "c:\users\atm\anaconda3\lib\site-packages\pdfforms\pdfforms.py", line 47, in load_field_defs
    with open(defs_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'fields.json'

**Comment by altaurog** [comment]
@andrewtmendoza, in the inspect stage, pdfforms generates a `fields.json` file.  By default it is saved in the current working directory, but an alternate location can be specified with `-f`.  This file is loaded during the fill stage.  Did you run `pdfforms inspect` with a different working directory?
